import {CONTENT_COLOR, CONTENT_COLOR_TWO, PRIMARY_COLOR, PRIMARY_COLOR_TWO, SUB_COLOR, SUB_COLOR_TWO} from "./color";

export const ICON_SIZE = {
    REGULAR: 20,
    EXTRA: 30,
    SMALL: 10,
};

export const ICON_COLOR = {
    PRIMARY_COLOR: PRIMARY_COLOR,
    SUB_COLOR: SUB_COLOR,
    PRIMARY_COLOR_TWO: PRIMARY_COLOR_TWO,
    SUB_COLOR_TWO: SUB_COLOR_TWO,
    CONTENT_COLOR: CONTENT_COLOR,
    CONTENT_COLOR_TWO: CONTENT_COLOR_TWO,
    BLACK: 'black',
    GREY: 'grey'
};